# =================== Filebeat inputs ===============================
filebeat.inputs:
- type: filestream
  id: nginx-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  fields:
    log_type: nginx
  fields_under_root: false

# ================================== Outputs ===================================
# Disable Elasticsearch output (we're using Logstash)
#output.elasticsearch:
#  hosts: ["https://localhost:9200"]

# Enable Logstash output
output.logstash:
  hosts: ["localhost:5044"]
  worker: 2
  compression_level: 3

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded

# ================================== Logging ===================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644